#!/usr/bin/env bash

echo "Usage: $0 [tcpdump arguments]"
echo "You may need to enter your password so TCPdump can connect to your adapater."
sudo echo "Now with the fun bit!"
echo "Running: tcpdump -e -l $@"
sudo tcpdump -e -l $@ | ruby macseen.rb
